### ISSUE TITLE
@RunWith( GuicyJUnit4 ) relies on outdated Guice code

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bufan1228/guiceyfruit#24]
```
When I try to use @RunWith and @UseModule, I get the following:

NoClassDefFoundError: com/google/inject/spi/CachingProvider

This class does not exist in any of the JARs in the Guice 2.0 release

```

Original issue reported on code.google.com by `tkshii` on 8 Jun 2009 at 2:39

**Comment by GoogleCodeExporter** [comment]
```
When call Injectors.close(injector), I get the following error:

java.lang.NoClassDefFoundError: com/google/inject/spi/CachedValue
    at org.guiceyfruit.Injectors.closeBinding(Injectors.java:378)
    at org.guiceyfruit.Injectors.close(Injectors.java:338)
    at org.guiceyfruit.Injectors.close(Injectors.java:310)
    at org.guiceyfruit.Injectors.close(Injectors.java:302)
```

Original comment by `jailjo...@gmail.com` on 12 Aug 2009 at 1:26

**Comment by GoogleCodeExporter** [comment]
```
Same problem here. Any news on this?
```

Original comment by `kaspar.f...@gmail.com` on 7 Feb 2010 at 2:49

**Comment by GoogleCodeExporter** [comment]
```
See also http://code.google.com/p/guiceyfruit/issues/detail?id=29
```

Original comment by `kaspar.f...@gmail.com` on 19 Feb 2010 at 5:43
