### ISSUE TITLE
Lifecycle don't work on binding to interface 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bufan1228/guiceyfruit#5]
```
My steps:
1. Get LifecycleTest from guice-jsr250 module 
2. Let's MyBean implements interface 
3. Bind this interface to MyBean in scope SINGLETON
4. Run test

Expected out is green line, but I have: 

junit.framework.AssertionFailedError: The pre destroy lifecycle should have 
been invoked on bean
    at 
com.google.inject.jsr250.LifecycleTest.testBeanInitialised(LifecycleTest.ja
va:54)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at 
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:3
9)
    at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImp
l.java:25)
    at 
com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at 
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:3
9)
    at 
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImp
l.java:25)
    at 
com.intellij.rt.execution.application.AppMain.main(AppMain.java:90)


I have found it in last trunk, OS - Windows XP, Java 1.6.0_11.

Test classes:

interface MyInterface {
}

public class LifecycleTest extends TestCase {

  public void testBeanInitialised() throws CreationException, 
CloseFailedException {
    Injector injector = Guice.createInjector(new AbstractModule() {
      protected void configure() {
        Jsr250.bind(binder());

        bind(MyInterface.class).to(MyBean.class).in(Singleton.class);
      }

    });

    MyBean bean = injector.getInstance(MyBean.class);
    assertNotNull("Should have instantiated the bean", bean);
    assertTrue("The post construct lifecycle should have been invoked on 
bean", bean.postConstruct);

    AnotherBean another = bean.another;
    assertNotNull("Should have instantiated the another", another);
    assertTrue("The post construct lifecycle should have been invoked on 
another", another.postConstruct);


    assertFalse("The pre destroy lifecycle not should have been invoked on 
bean", bean.preDestroy);
    injector.close();
    assertTrue("The pre destroy lifecycle should have been invoked on 
bean", bean.preDestroy);
  }

  static class MyBean implements MyInterface {
    @Inject
    public AnotherBean another;

    public boolean postConstruct;
    public boolean preDestroy;

    @PostConstruct
    public void postConstruct() throws Exception {
      postConstruct = true;
    }

    @PreDestroy
    public void preDestroy() throws Exception {
      preDestroy = true;
    }
  }

  static class AnotherBean {
    public boolean postConstruct;

    @PostConstruct
    public void postConstruct() throws Exception {
      postConstruct = true;
    }
  }
}







```

Original issue reported on code.google.com by `aleksey....@gmail.com` on 27 Mar 2009 at 8:48

**Comment by GoogleCodeExporter** [comment]
```
Sorry, my error.
In my example I call 

MyBean bean = injector.getInstance(MyBean.class);

instead of 

MyBean bean = (MyBean) injector.getInstance(MyInterface.class);

In second case all work right.
Sorry for wasting your time.



```

Original comment by `aleksey....@gmail.com` on 27 Mar 2009 at 9:50

**Comment by GoogleCodeExporter** [comment]
```
DOH :) I just fell for the same issue as you did trying to reproduce it - I 
missed your second comment :). 

Many thanks for the update!

FWIW I've checked in a version of your test case that includes both of our 
mistakes - and the correct way in 
separate test methods...

http://code.google.com/p/guiceyfruit/source/browse/trunk/guiceyfruit-
core/src/test/java/org/guiceyfruit/jsr250/LifecycleWithInterfaceTest.java
```

Original comment by `james.st...@gmail.com` on 7 Apr 2009 at 8:08
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `james.st...@gmail.com` on 7 Apr 2009 at 12:23
- Added labels: **Milestone-2.0-beta-6**
